### ISSUE TITLE
Chrome driver out out of date, how to update?

### ISSUE THREAD

**Issue by theoinkinator** [romazhan/chess-bot#2]
Message: unknown error: cannot connect to chrome at xxx.xx.xxx.xxx
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.111

**Comment by romazhan** [comment]
Thank you for this issue. I have updated the file `requirements.txt`

**Comment by theoinkinator** [comment]
Any chance you can make it move automatically but in a "legitmate" way

**Comment by romazhan** [comment]
I don't remember exactly, but I don't think I was able to simulate a "move" from JavaScript. Maybe you can do it, here are some tips:

```js
// to simulate a move, but it seems that some other
// event is required to fully simulate the movement
document.body.querySelector('.board').game.move('e2e4');

// to publish a new event
document.body.querySelector('.board').game.emit('Move', {
    data: ?
});

// to handle all events
document.body.querySelector('.board').game.onAll(data => console.log(data));
```

I also found some kind of event listener associated with cheats, so most likely if you manage to simulate a move from the game object, then you will be banned:

```js
document.body.querySelector('.board').game.getContext().emitter.listeners[1];
```

I think I've seen something else related to cheats, but it's not accurate.

I was able to reach a rating of 2500 using my bot and my account still hasn't been banned. It is very difficult to write a robot that will make human mistakes and have different time delays depending on the complexity of the position. In addition, if the robot makes moves by itself, it will not be so much fun for a human.

**Comment by theoinkinator** [comment]
Thank you, I'll see what I can do. But, if you can't figure it out I probably can't either, and ban rate would be higher so in the end manually moving the pieces is the way to go.

I managed to play at 2k rating for awhile without getting banned, until I played 1 minute blitz which I assume is what got me banned due to the high accuracy for 1 minute games. What engine configs do you use?

Really been enjoying this release btw, great work.

**Comment by romazhan** [comment]
Thanks for the feedback.
My `config.ini` for playing blitz/bullet:

```ini
[SURFACE]
stop_commands = (exit, stop, close)
hint_lighting = (e2859a, bd7873)

[ENGINE]
path = ./engines/stockfish-17/stockfish-windows-x86-64-avx2.exe
move_max_time = 250
threads = 12
hash = 1024
elo = 3190
depth = 20
contempt = 0

[BROWSER]
version_main = 150
start_url = https://www.chess.com/play/online
use_existing_profile = false

[SERVER]
port = 8123
```
